name: Publish to PyPI
on: 
  push:
    branchs:
      - master
    tags:
      - '*'
jobs:
  sync:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}